import type { HistoricalBar, MarketDataProvider, ProviderNews, ProviderQuote } from "./types";
const idMap: Record<string, string> = { "BTC-USD": "bitcoin", "ETH-USD": "ethereum", "SOL-USD": "solana" };
export function coingeckoProvider(apiKey?: string): MarketDataProvider {
  async function fetchJson(path: string, params: Record<string, string> = {}) { const url = new URL(`https://api.coingecko.com/api/v3${path}`); Object.entries(params).forEach(([k, v]) => url.searchParams.set(k, v)); const headers: Record<string, string> = {}; if (apiKey) headers["x-cg-demo-api-key"] = apiKey; const response = await fetch(url, { headers }); const json = await response.json(); if (!response.ok) throw new Error(`CoinGecko request failed: ${json.error || response.statusText}`); return json; }
  return {
    name: "coingecko",
    async getQuote(symbol: string): Promise<ProviderQuote> { const id = idMap[symbol] ?? symbol.toLowerCase().replace("-usd", ""); const json = await fetchJson("/simple/price", { ids: id, vs_currencies: "usd", include_market_cap: "true", include_24hr_vol: "true", include_24hr_change: "true", include_last_updated_at: "true" }); const row = json[id]; if (!row) throw new Error(`CoinGecko quote missing for ${symbol}`); return { symbol, price: Number(row.usd), previousClose: Number(row.usd) / (1 + Number(row.usd_24h_change ?? 0) / 100), changePercent: Number(row.usd_24h_change ?? 0), volume: Number(row.usd_24h_vol ?? 0) || null, marketCap: Number(row.usd_market_cap ?? 0) || null, timestamp: row.last_updated_at ? new Date(row.last_updated_at * 1000).toISOString() : new Date().toISOString(), provider: "coingecko", dataStatus: "Delayed", raw: row }; },
    async getHistoricalBars(symbol: string, interval: "1d" | "5m"): Promise<HistoricalBar[]> { const id = idMap[symbol] ?? symbol.toLowerCase().replace("-usd", ""); const json = await fetchJson(`/coins/${id}/market_chart`, { vs_currency: "usd", days: interval === "1d" ? "max" : "1" }); return (json.prices ?? []).map(([time, close]: [number, number], i: number) => ({ symbol, interval, timestamp: new Date(time).toISOString(), open: Number(i ? json.prices[i - 1][1] : close), high: Number(close), low: Number(close), close: Number(close), adjustedClose: Number(close), volume: Number(json.total_volumes?.[i]?.[1] ?? 0) || null, provider: "coingecko", dataQuality: "normal" })); },
    async getBatchQuotes(symbols: string[]) { const settled = await Promise.allSettled(symbols.map((symbol) => this.getQuote(symbol))); return settled.flatMap((r) => r.status === "fulfilled" ? [r.value] : []); },
    async getNews(): Promise<ProviderNews[]> { return []; }
  };
}
